import Hero from "@/sections/Hero";
import { Metadata } from "next/types";
import Inquiry from "@/sections/Inquiry";
import Products from "@/sections/Products";
import Testimonials from "@/sections/Testimonials";
import AboutSection from "@/sections/About/AboutSection";
import ScrollUp from "@/components/ScrollToTop/ScrollUp";

export const metadata: Metadata = {
  title: "Askitect",
  description: "Generated by Askitect",
};

export default function Home() {
  return (
    <>
      <ScrollUp />
      <Hero />
      <Products />
      <AboutSection />
      <Testimonials />
      <Inquiry />
    </>
  );
}
